### ISSUE TITLE
Updating README: code coverage reporting and publishing and more

### ISSUE THREAD

**Issue by jb-adams** [ga4gh/ga4gh-starter-kit-common#41]
* improve code coverage if possible
* ensure coverage reports are being submitted to [codecov](https://about.codecov.io/) during CI, potentially use an existing Github Action to do this
* add coverage badge from codecov to README

**Comment by emre-f** [comment]
Changed the title, the issue includes:
- Showing if the GitHub actions workflow build passes
- Also showing accurate java and gradle versions

**Comment by jb-adams** [comment]
closing issue with merge of #44
